//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H


#include <string>
#include <vector>

#include "User.h"

using namespace std;

class Wyklad;
class Materialy;

class Student : public User {
public:
	Student(string imie, string nazwisko, int numerAlbumu, string haslo);
	~Student();
	string getImie();
	string getNazwisko();
	int getNumerAlbumu();
	vector<Wyklad*> getListaWykladow();
	void setImie(string imie);
	void setNazwisko(string nazwisko);
	void setNumerAlbumu(int numer);
	void dodajDoWykladu(Wyklad* wyklad);
	void usunWyklad(Wyklad* wyklad);
	vector<Materialy*> przegladajMaterialy(Wyklad* wyklad);
private:
	string Imie;
	string Nazwisko;
	int NumerAlbumu;
	vector<Wyklad*> ListaWykladow;
};

#endif  //_STUDENT_H
