//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//

#include "Student.h"
#include "Wykladowca.h"
#include "Uczelnia.h"
#include "Wydzial.h"
#include "Wyklad.h"
#include "testy.h"

#include <iostream>
#include <algorithm>

Uczelnia::Uczelnia(string nazwa, vector<Wydzial*> wydzialy) {
    this->Nazwa = nazwa;
    this->ListaWydzialow = wydzialy;
}

Uczelnia::~Uczelnia() {
    for (Wydzial* wydzial : this->ListaWydzialow) {
        delete wydzial;
    }
}

string Uczelnia::getNazwa() {
    return this->Nazwa;
}

vector<Student*> Uczelnia::getListaStudentow() {
    return this->ListaStudentow;
}

vector<Wykladowca*> Uczelnia::getListaWykladowcow() {
    return this->ListaWykladowcow;
}

vector<Wydzial*> Uczelnia::getListaWydzialow() {
    return this->ListaWydzialow;
}

void Uczelnia::setNazwa(string nazwa) {
    this->Nazwa = nazwa;
}

void Uczelnia::dodajStudenta(Student* student) {
    for (Student* stud: this->ListaStudentow)
    {
        if (stud == student){
            cout<<"Student jest juz przypisany do uczelni." << endl;
            return;
        }
    }

    this->ListaStudentow.push_back(student);
}

void Uczelnia::usunStudenta(Student* student) {
    //usuniecie jako wykreslenie z listy uczelni / wywolanie destruktora

    for (Student* stud: this->ListaStudentow)
    {
        if (stud == student){
            this->ListaStudentow.erase(find(this->ListaStudentow.begin(), this->ListaStudentow.end(), stud));
            delete stud;
            return;
        }
    }
}

void Uczelnia::dodajWykladowce(Wykladowca* wykladowca) {
    for (Wykladowca* wyk: this->ListaWykladowcow)
    {
        if (wyk == wykladowca){
            this->ListaWykladowcow.erase(find(this->ListaWykladowcow.begin(), this->ListaWykladowcow.end(), wyk));
            cout<<"Wykladowca jest juz przypisany do uczelni." << endl;
            return;
        }
    }

    this->ListaWykladowcow.push_back(wykladowca);
}

void Uczelnia::usunWykladowce(Wykladowca* wykladowca) {
    //usuniecie jako wykreslenie z listy uczelni / wywolanie destruktora
    for (Wykladowca* wyk: this->ListaWykladowcow)
    {
        if (wyk == wykladowca){
            delete wyk;
            return;
        }
    }
}

char Uczelnia::Zaloguj(string login, string haslo) {
    for (Student* s : this->ListaStudentow) {
        if (s->getLogin() == login && s->getHaslo() == haslo) {
            cout << "Zalogowano pomyslnie jako Student: " << login << endl;
            return 's';
        }
    }

    for (Wykladowca* w : this->ListaWykladowcow) {
        if (w->getLogin() == login && w->getHaslo() == haslo) {
            std::cout << "Zalogowano pomyslnie jako Wykladowca: " << login << endl;
            return 'w';
        }
    }
    
    cout << "Blad logowania."<< endl;
    return 'f';
}

void Uczelnia::ZmianaHasla(string login, string stareHaslo, string noweHaslo) {
    for (Student* s : this->ListaStudentow) {
        if (s->getLogin() == login && s->getHaslo() == stareHaslo) {
            s->setHaslo(noweHaslo);
            std::cout << "Haslo studenta " << login << " zostalo zmienione pomyslnie." << endl;
            return;
        }
    }

    for (Wykladowca* w : this->ListaWykladowcow) {
        if (w->getLogin() == login && w->getHaslo() == stareHaslo) {
             w->setHaslo(noweHaslo);
            std::cout << "Haslo wykladowcy " << login << " zostalo zmienione pomyslnie." << endl;
            return;
        }
    }

    cout << "Blad zmiany hasla: Niewlasciwe dane uwierzytelniajace.";
}

////////////////////////////



int main(){
    /*
    // Wydziały
    Wydzial* wydzInformatyki = new Wydzial("Wydzial Informatyki");
    Wydzial* wydzMatematyki = new Wydzial("Wydzial Matematyki");

    vector<Wydzial*> wszystkieWydzialy;
    wszystkieWydzialy.push_back(wydzInformatyki);
    wszystkieWydzialy.push_back(wydzMatematyki);

    // Uczelnia
    Uczelnia* uczelnia = new Uczelnia("UMCS", wszystkieWydzialy);
    cout << "Utworzono uczelnie: " << uczelnia->getNazwa() << endl;

    // Wyklady
    Wyklad* wykInf1 = new Wyklad("Programowanie C++", wydzInformatyki);
    Wyklad* wykInf2 = new Wyklad("Bazy Danych", wydzInformatyki);
    Wyklad* wykInf3 = new Wyklad("Sieci Komputerowe", wydzInformatyki);


    Wyklad* wykMat1 = new Wyklad("Analiza Matematyczna", wydzMatematyki);
    Wyklad* wykMat2 = new Wyklad("Algebra Liniowa", wydzMatematyki);
    Wyklad* wykMat3 = new Wyklad("Rachunek Prawdopodobienstwa", wydzMatematyki);

    // Studenci
    Student* s1 = new Student("Jan", "Kowalski", 100111, "haslo1");
    Student* s2 = new Student("Anna", "Nowak", 100222, "haslo2");
    Student* s3 = new Student("Piotr", "Wisniewski", 100333, "haslo3");
    Student* s4 = new Student("Katarzyna", "Zielinska", 100444, "haslo4");

    uczelnia->dodajStudenta(s1);
    uczelnia->dodajStudenta(s2);
    uczelnia->dodajStudenta(s3);
    uczelnia->dodajStudenta(s4);

    // Wykładowcy
    Wykladowca* w1 = new Wykladowca("Alan", "Turing", "aturing", "tajne123");
    Wykladowca* w2 = new Wykladowca("Ada", "Lovelace", "alovelace", "tajne456");

    uczelnia->dodajWykladowce(w1);
    uczelnia->dodajWykladowce(w2);

    // Przypisanie Wykładowców
    wykInf1->dodajWykladowce(w1);
    wykInf2->dodajWykladowce(w1);
    wykMat1->dodajWykladowce(w2);

    for(Wykladowca* wyk : wykInf1->getListaWykladowcow()){
        cout<< "Prowadzacy: " << wyk->getImie() << " " << wyk->getNazwisko() << endl;
    }

    // Przypisanie Studentów
    wykInf1->dodajStudenta(s1);
    wykInf1->dodajStudenta(s2);

    wykInf2->dodajStudenta(s2);
    wykInf2->dodajStudenta(s3);

    wykMat1->dodajStudenta(s1);
    wykMat1->dodajStudenta(s4);

    for(Student* stud : wykInf1->getListaStudentow()){
        cout<< "Student: " << stud->getImie() << " " << stud->getNazwisko() << endl;
    }

    // Logowanie
    uczelnia->Zaloguj("100111", "haslo1");    // Logowanie s1 (zwróci sukces)
    uczelnia->Zaloguj("aturing", "tajne123"); // Logowanie w1 (zwróci sukces)
    uczelnia->Zaloguj("100222", "zlehaslo");  // Bledne haslo

    delete uczelnia;


    cout << "Program zakonczyl dzialanie pomyslnie." << endl;

    int k;

    cin >> k;

    return 0;
    */
    Wydzial* wydzInformatyki = new Wydzial("Wydzial Informatyki");
    Wydzial* wydzMatematyki = new Wydzial("Wydzial Matematyki");

    vector<Wydzial*> wszystkieWydzialy;
    wszystkieWydzialy.push_back(wydzInformatyki);
    wszystkieWydzialy.push_back(wydzMatematyki);

    // Uczelnia
    Uczelnia* uczelnia = new Uczelnia("UMCS", wszystkieWydzialy);

    // Wyklady
    Wyklad* wykInf1 = new Wyklad("Programowanie C++", wydzInformatyki);
    Wyklad* wykInf2 = new Wyklad("Bazy Danych", wydzInformatyki);
    Wyklad* wykInf3 = new Wyklad("Sieci Komputerowe", wydzInformatyki);


    Wyklad* wykMat1 = new Wyklad("Analiza Matematyczna", wydzMatematyki);
    Wyklad* wykMat2 = new Wyklad("Algebra Liniowa", wydzMatematyki);
    Wyklad* wykMat3 = new Wyklad("Rachunek Prawdopodobienstwa", wydzMatematyki);

    // Studenci
    Student* s1 = new Student("Jan", "Kowalski", 100111, "haslo1");
    Student* s2 = new Student("Anna", "Nowak", 100222, "haslo2");
    Student* s3 = new Student("Piotr", "Wisniewski", 100333, "haslo3");
    Student* s4 = new Student("Katarzyna", "Zielinska", 100444, "haslo4");

    uczelnia->dodajStudenta(s1);
    uczelnia->dodajStudenta(s2);
    uczelnia->dodajStudenta(s3);
    uczelnia->dodajStudenta(s4);

    // Wykładowcy
    Wykladowca* w1 = new Wykladowca("Alan", "Turing", "aturing", "tajne123");
    Wykladowca* w2 = new Wykladowca("Ada", "Lovelace", "alovelace", "tajne456");

    uczelnia->dodajWykladowce(w1);
    uczelnia->dodajWykladowce(w2);

    // Przypisanie Wykładowców
    wykInf1->dodajWykladowce(w1);
    wykInf2->dodajWykladowce(w1);
    wykMat1->dodajWykladowce(w2);

    // Przypisanie Studentów
    wykInf1->dodajStudenta(s1);
    wykInf1->dodajStudenta(s2);

    wykInf2->dodajStudenta(s2);
    wykInf2->dodajStudenta(s3);

    wykMat1->dodajStudenta(s1);
    wykMat1->dodajStudenta(s4);

    string login,haslo;
    char decyzja;

    cout << "Witaj na uczelni!" << endl;
    cout << "Zaloguj się:" << endl;

        while(1){


        cin >> login >> haslo;

        switch (uczelnia->Zaloguj(login, haslo)){
        case 's':{
            while(1){
            cout << "Wybierz numer:" << endl;
            cout << "5.Wyloguj" << endl;
            cin >> decyzja;

            switch (decyzja) {
            case '5':{
                return 0;
            }
            }
            }
            break;
        }

        case 'w':{
            while(1){
            cout << "Wybierz numer:" << endl;
            cout << "5.Wyloguj" << endl;
            cin >> decyzja;

            switch (decyzja) {
            case '5':{
                return 0;
            }
            }
            }
            break;
        }
        case 'f':{
            cout << "Zaloguj się ponownie:" << endl;
        }
        }


    }

    return 0;
}
