//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Materialy.h
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#if !defined(_MATERIALY_H)
#define _MATERIALY_H

#include <string>

using namespace std;

class Materialy {
public:
	Materialy(string nazwa, string rodzaj);
	~Materialy();
	string getNazwa();
	string getRodzaj();
	void setNazwa(string nazwa);
	void setRodzaj(string rodzaj);
private:
	string Nazwa;
	string Rodzaj;
};

#endif  //_MATERIALY_H
