//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Materialy.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#include "Materialy.h"
#include <string>

using namespace std;

Materialy::Materialy(string nazwa, string rodzaj) {
    this->Nazwa = nazwa;
    this->Rodzaj = rodzaj;
}

Materialy::~Materialy() {

}

string Materialy::getNazwa() {
    return this->Nazwa;
}

string Materialy::getRodzaj() {
    return this->Rodzaj;
}

void Materialy::setNazwa(string nazwa) {
    this->Nazwa = nazwa;
}

void Materialy::setRodzaj(string rodzaj) {
    this->Rodzaj = rodzaj;
}

