//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//

#include "Student.h"
#include "Wyklad.h"
#include <iostream>
#include <algorithm> // Wymagane dla funkcji find()

Student::Student(string imie, string nazwisko, int numerAlbumu, string haslo) : User(to_string(numerAlbumu), haslo) {
    this->Imie = imie;
    this->Nazwisko = nazwisko;
    this->NumerAlbumu = numerAlbumu;
}

Student::~Student() {
    for (Wyklad* wyklad: this->ListaWykladow)
    {
        wyklad->usunStudenta(this);
    }
}

string Student::getImie() {
    return this->Imie;
}

string Student::getNazwisko() {
    return this->Nazwisko;
}

int Student::getNumerAlbumu() {
    return this->NumerAlbumu;
}

vector<Wyklad*> Student::getListaWykladow() {
    return this->ListaWykladow;
}

void Student::setImie(string imie) {
    this->Imie = imie;
}

void Student::setNazwisko(string nazwisko) {
    this->Nazwisko = nazwisko;
}

void Student::setNumerAlbumu(int numer) {
    this->NumerAlbumu = numer;
}

void Student::dodajDoWykladu(Wyklad* wyklad) {
    //dodawanie musi odbywać się na rzecz obiektu wykład!
    for (Wyklad* wyk: this->ListaWykladow)
    {
        if (wyk == wyklad){
            cout<<"Student ma juz przypisany ten wyklad." << endl;
            return;
        }
    }

    this->ListaWykladow.push_back(wyklad);
}

void Student::usunWyklad(Wyklad* wyklad) {
    vector<Wyklad*> wyklady = this->ListaWykladow;
    for (Wyklad* wyk: wyklady)
    {
        if (wyk == wyklad){
            wyklady.erase(find(wyklady.begin(), wyklady.end(), wyklad));
            return;
        }
    }

    cout<<"Student nie ma przypisanego tego wykladu." << endl;
}

vector<Materialy*> Student::przegladajMaterialy(Wyklad* wyklad) {
    return wyklad->getListaMaterialow();
}

