//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#include "Student.h"
#include "Wyklad.h"

#include <algorithm>
#include <iostream>


Student::Student(string imie, string nazwisko, int numerAlbumu, string haslo) : User(to_string(numerAlbumu), haslo) {
    this->Imie = imie;
    this->Nazwisko = nazwisko;
    this->NumerAlbumu = numerAlbumu;
}

Student::~Student() {
    for (Wyklad* wyklad: this->getListaWykladow())
    {
        wyklad->usunStudenta(this);
    }
}

string Student::getImie() {
    return this->Imie;
}

string Student::getNazwisko() {
    return this->Nazwisko;
}

int Student::getNumerAlbumu() {
    return this->NumerAlbumu;
}

vector<Wyklad*> Student::getListaWykladow() {
    return this->ListaWykladow;
}

void Student::setImie(string imie) {
    this->Imie = imie;
}

void Student::setNazwisko(string nazwisko) {
    this->Nazwisko = nazwisko;
}

void Student::setNumerAlbumu(int numer) {
    this->NumerAlbumu = numer;
}

void Student::dodajDoWykladu(Wyklad* wyklad) {
    auto it = find(this->ListaWykladow.begin(), this->ListaWykladow.end(), wyklad);
    if (it == this->ListaWykladow.end()) {
        this->ListaWykladow.push_back(wyklad);
        wyklad->dodajStudenta(this);
    }
}

void Student::dolaczDoWykladu(Wyklad* wyklad, string haslo) {
    if (wyklad->getHaslo() == haslo) {
        this->dodajDoWykladu(wyklad);
        cout << "Pomyslnie dolaczono do wykladu: " << wyklad->getNazwa() << endl;
    } else {
        cout << "Blad: Niepoprawne haslo do wykladu!" << endl;
    }
}

void Student::usunWyklad(Wyklad* wyklad) {

    auto it = find(this->ListaWykladow.begin(), this->ListaWykladow.end(), wyklad);
    if (it != this->ListaWykladow.end()) {
        this->ListaWykladow.erase(it);
    }
}

vector<Materialy*> Student::przegladajMaterialy(Wyklad* wyklad) {
    return wyklad->getListaMaterialow();
}

