//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.h
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#if !defined(_UCZELNIA_H)
#define _UCZELNIA_H

#include <string>
#include <vector>

using namespace std;

class Student;
class Wykladowca;
class Wydzial;

class Uczelnia {
public:
	Uczelnia(string nazwa, vector<Wydzial*> wydzialy);
	~Uczelnia();
	string getNazwa();
	vector<Student*> getListaStudentow();
	vector<Wykladowca*> getListaWykladowcow();
	vector<Wydzial*> getListaWydzialow();
	void setNazwa(string nazwa);
	void dodajStudenta(Student* student);
	void usunStudenta(Student* student);
	void dodajWykladowce(Wykladowca* wykladowca);
	void usunWykladowce(Wykladowca* wykladowca);
    char Zaloguj(string login, string haslo);
	void ZmianaHasla(string login, string stareHaslo, string noweHaslo);
    Student* znajdzStudenta(string login);
    Wykladowca* znajdzWykladowce(string login);
private:
	string Nazwa;
	vector<Student*> ListaStudentow;
	vector<Wykladowca*> ListaWykladowcow;
	vector<Wydzial*> ListaWydzialow;
};

#endif  //_UCZELNIA_H
