//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//

#include "Student.h"
#include "Materialy.h"
#include "Wykladowca.h"
#include "Uczelnia.h"
#include "Wydzial.h"
#include "Wyklad.h"
#include "testy.h"

#include <iostream>
#include <algorithm>

Uczelnia::Uczelnia(string nazwa, vector<Wydzial*> wydzialy) {
    this->Nazwa = nazwa;
    this->ListaWydzialow = wydzialy;
}

Uczelnia::~Uczelnia() {
    for (Wydzial* wydzial : this->ListaWydzialow) {
        delete wydzial;
    }
    for (Student* student : this->ListaStudentow) {
        delete student;
    }
    for (Wykladowca* wykladowca : this->ListaWykladowcow) {
        delete wykladowca;
    }
}

string Uczelnia::getNazwa() {
    return this->Nazwa;
}

vector<Student*> Uczelnia::getListaStudentow() {
    return this->ListaStudentow;
}

vector<Wykladowca*> Uczelnia::getListaWykladowcow() {
    return this->ListaWykladowcow;
}

vector<Wydzial*> Uczelnia::getListaWydzialow() {
    return this->ListaWydzialow;
}

void Uczelnia::setNazwa(string nazwa) {
    this->Nazwa = nazwa;
}

void Uczelnia::dodajStudenta(Student* student) {
    auto it = find(this->ListaStudentow.begin(), this->ListaStudentow.end(), student);
    if (it == this->ListaStudentow.end()) {
        this->ListaStudentow.push_back(student);
    }
}

void Uczelnia::usunStudenta(Student* student) {
    //usuniecie jako wykreslenie z listy uczelni / wywolanie destruktora

    auto it = find(this->ListaStudentow.begin(), this->ListaStudentow.end(), student);
    if (it != this->ListaStudentow.end()) {
        Student* doUsuniecia = *it;
        this->ListaStudentow.erase(it);
        delete doUsuniecia;
    }
}

void Uczelnia::dodajWykladowce(Wykladowca* wykladowca) {
    auto it = find(this->ListaWykladowcow.begin(), this->ListaWykladowcow.end(), wykladowca);
    if (it == this->ListaWykladowcow.end()) {
        this->ListaWykladowcow.push_back(wykladowca);
    }
}

void Uczelnia::usunWykladowce(Wykladowca* wykladowca) {
    //usuniecie jako wykreslenie z listy uczelni / wywolanie destruktora

    auto it = find(this->ListaWykladowcow.begin(), this->ListaWykladowcow.end(), wykladowca);
    if (it != this->ListaWykladowcow.end()) {
        Wykladowca* doUsuniecia = *it;
        this->ListaWykladowcow.erase(it);
        delete doUsuniecia;
    }
}

Student* Uczelnia::znajdzStudenta(string login){
    for (Student* s : this->ListaStudentow) {
        if (s->getLogin() == login) {
            return s;
        }
    }
    return nullptr;
}

Wykladowca* Uczelnia::znajdzWykladowce(string login){
    for (Wykladowca* w : this->ListaWykladowcow) {
        if (w->getLogin() == login) {
            return w;
        }
    }
    return nullptr;
}

char Uczelnia::Zaloguj(string login, string haslo) {
    for (Student* s : this->ListaStudentow) {
        if (s->getLogin() == login && s->getHaslo() == haslo) {
            cout << "Zalogowano pomyslnie jako Student: " << login << endl;
            return 's';
        }
    }

    for (Wykladowca* w : this->ListaWykladowcow) {
        if (w->getLogin() == login && w->getHaslo() == haslo) {
            cout << "Zalogowano pomyslnie jako Wykladowca: " << login << endl;
            return 'w';
        }
    }
    
    cout << "Blad logowania."<< endl;
    return 'f';
}

void Uczelnia::ZmianaHasla(string login, string stareHaslo, string noweHaslo) {
    for (Student* s : this->ListaStudentow) {
        if (s->getLogin() == login && s->getHaslo() == stareHaslo) {
            s->setHaslo(noweHaslo);
            cout << "Haslo studenta " << login << " zostalo zmienione pomyslnie." << endl;
            return;
        }
    }

    for (Wykladowca* w : this->ListaWykladowcow) {
        if (w->getLogin() == login && w->getHaslo() == stareHaslo) {
             w->setHaslo(noweHaslo);
            cout << "Haslo wykladowcy " << login << " zostalo zmienione pomyslnie." << endl;
            return;
        }
    }

    cout << "Blad zmiany hasla: Niewlasciwe dane uwierzytelniajace." << endl;;
}

////////////////////////////



int main(){
    cout << "=== 1. INICJALIZACJA SYSTEMU ===" << endl;

    // Wydziały
    Wydzial* wydzInformatyki = new Wydzial("Wydzial Informatyki");
    Wydzial* wydzMatematyki = new Wydzial("Wydzial Matematyki");

    vector<Wydzial*> wszystkieWydzialy;
    wszystkieWydzialy.push_back(wydzInformatyki);
    wszystkieWydzialy.push_back(wydzMatematyki);

    // Uczelnia
    Uczelnia* uczelnia = new Uczelnia("Uniwersytet Marii Curie-Sklodowskiej", wszystkieWydzialy);
    cout << "Utworzono uczelnie: " << uczelnia->getNazwa() << endl;

    // Studenci
    Student* s1 = new Student("Jan", "Kowalski", 100111, "haslo1");
    Student* s2 = new Student("Anna", "Nowak", 100222, "haslo2");
    uczelnia->dodajStudenta(s1);
    uczelnia->dodajStudenta(s2);

    // Wykładowcy
    Wykladowca* w1 = new Wykladowca("Alan", "Turing", "aturing", "tajne123");
    Wykladowca* w2 = new Wykladowca("Ada", "Lovelace", "alovelace", "tajne456");
    uczelnia->dodajWykladowce(w1);
    uczelnia->dodajWykladowce(w2);

    cout << "Zarejestrowano studentow i wykladowcow.\n" << endl;

    cout << "=== 2. TWORZENIE WYKLADOW ===" << endl;
    Wyklad* wykInf1 = w1->utworzWyklad(wydzInformatyki, "Programowanie C++");
    wykInf1->setHaslo("cpp2026");
    cout << "Wykladowca " << w1->getNazwisko() << " utworzyl wyklad: " << wykInf1->getNazwa() << " (Z HASLEM)." << endl;

    Wyklad* wykMat1 = w2->utworzWyklad(wydzMatematyki, "Analiza Matematyczna");
    cout << "Wykladowca " << w2->getNazwisko() << " utworzyl wyklad: " << wykMat1->getNazwa() << " (BEZ HASLA)." << endl;


    cout << "\n=== 3. DODAWANIE MATERIALOW ===" << endl;
    w1->dodajMaterialy(wykInf1, new Materialy("Wstep do C++", "Prezentacja PDF"));
    w1->dodajMaterialy(wykInf1, new Materialy("Zadanie 1: Klasy", "Plik TXT"));
    w1->dodajMaterialy(wykInf1, new Materialy("Kolokwium próbne", "Skrypt .sh"));

    w2->dodajMaterialy(wykMat1, new Materialy("Calki - Teoria", "Dokument PDF"));
    w2->dodajMaterialy(wykMat1, new Materialy("Zestaw zadan", "Plik DOCX"));

    cout << "Pomyslnie przypisano materialy do kursow.\n" << endl;


    cout << "=== 4. DOLACZANIE DO WYKLADOW ===" << endl;
    cout << "Student " << s1->getImie() << " probuje dolaczyc do 'Programowanie C++' podajac zle haslo:" << endl;
    s1->dolaczDoWykladu(wykInf1, "zle_haslo");

    cout << "\nStudent " << s1->getImie() << " probuje dolaczyc podajac prawidlowe haslo:" << endl;
    s1->dolaczDoWykladu(wykInf1, "cpp2026");

    wykMat1->dodajStudenta(s2);
    cout << "Studentka " << s2->getImie() << " zostala recznie zapisana na wyklad z Analizy.\n" << endl;


    cout << "=== 5. PREZENTACJA WYNIKOW ===" << endl;
    cout << "Materialy dostepne dla studenta " << s1->getImie() << " na wykladzie " << wykInf1->getNazwa() << ":" << endl;
    for(Materialy* mat : s1->przegladajMaterialy(wykInf1)){
        cout << " -> " << mat->getNazwa() << " [" << mat->getRodzaj() << "]" << endl;
    }


    cout << "\n=== 6. URUCHOMIENIE TESTOW JEDNOSTKOWYCH ===" << endl;
    testy();

    cout << "\n=== 7. URUCHOMIENIE GLOWNEGO MENU ===" << endl;
    while(1){
        petla(uczelnia);
    }

    delete uczelnia;

    return 0;
}
