//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#include "User.h"
#include <string>

using namespace std;

User::User(string login, string haslo) {
    this->Login = login;
    this->Haslo = haslo;
}

User::~User() {

}

string User::getLogin() {
    return this->Login;
}

string User::getHaslo() {
    return this->Haslo;
}

void User::setHaslo(string haslo){
    this->Haslo = haslo;
}