//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.h
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#if !defined(_USER_H)
#define _USER_H

#include <string>

using namespace std;

class User {
public:
	User(string login, string haslo);
	~User();
	string getLogin();
	string getHaslo();
	void setHaslo(string haslo);
private:
	string Login;
	string Haslo;
};

#endif  //_USER_H
