//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wydzial.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//

#include "Wydzial.h"
#include "Wyklad.h"
#include <iostream>

Wydzial::Wydzial(string nazwa) {
    this->Nazwa = nazwa;
}

Wydzial::~Wydzial() {
    for(Wyklad* wyk : this->ListaWykladow){
        delete wyk;
    }
}

string Wydzial::getNazwa() {
    return this->Nazwa;
}

vector<Wyklad*> Wydzial::getListaWykladow() {
    return this->ListaWykladow;
}

void Wydzial::setNazwa(string nazwa) {
    this->Nazwa = nazwa;
}

void Wydzial::dodajNowyWyklad(Wyklad* wyklad) {
    for (Wyklad* wyk: this->ListaWykladow)
    {
        if (wyk == wyklad){
            cout<<"Wyklad jest juz przypisany." << endl;
            return;
        }
    }

    this->ListaWykladow.push_back(wyklad);
}

void Wydzial::usunWyklad(Wyklad* wyklad) {
    for (Wyklad* wyk: this->ListaWykladow)
    {
        if (wyk == wyklad){
            delete wyk;
            return;
        }
    }

    cout<<"Brak wykladu do usuniecia." << endl;
}

