//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wydzial.h
//  @ Date : 24.05.2026
//  @ Author : 
//
//

#if !defined(_WYDZIAL_H)
#define _WYDZIAL_H



#include <string>
#include <vector>

using namespace std;

class Wyklad;

class Wydzial {
public:
	Wydzial(string nazwa);
	~Wydzial();
    string getNazwa();
	vector<Wyklad*> getListaWykladow();
	void setNazwa(string nazwa);
	void dodajNowyWyklad(Wyklad* wyklad);
	void usunWyklad(Wyklad* wyklad);
private:
    string Nazwa;
	vector<Wyklad*> ListaWykladow;
};

#endif  //_WYDZIAL_H
