//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wydzial.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//

#include "Wydzial.h"
#include "Wyklad.h"

Wydzial::Wydzial(string nazwa) {
    this->Nazwa = nazwa;
}

Wydzial::~Wydzial() {
    for(Wyklad* wyk : this->ListaWykladow){
        wyk->setWydzial(nullptr);
        delete wyk;
    }
}

string Wydzial::getNazwa() {
    return this->Nazwa;
}

vector<Wyklad*> Wydzial::getListaWykladow() {
    return this->ListaWykladow;
}

void Wydzial::setNazwa(string nazwa) {
    this->Nazwa = nazwa;
}

void Wydzial::dodajNowyWyklad(Wyklad* wyklad) {
    auto it = find(this->ListaWykladow.begin(), this->ListaWykladow.end(), wyklad);
    if (it == this->ListaWykladow.end()) {
        this->ListaWykladow.push_back(wyklad);
    }
}

void Wydzial::usunWyklad(Wyklad* wyklad) {
    auto it = find(this->ListaWykladow.begin(), this->ListaWykladow.end(), wyklad);
    if (it != this->ListaWykladow.end()) {
        Wyklad* doUsuniecia = *it;
        this->ListaWykladow.erase(it);
        delete doUsuniecia;
    }
}

