//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wyklad.h
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#if !defined(_WYKLAD_H)
#define _WYKLAD_H

#include <string>
#include <vector>

using namespace std;

class Student;
class Wykladowca;
class Materialy;
class Wydzial;

class Wyklad {
public:
    Wyklad(string nazwa, Wydzial* wydzial);
	~Wyklad();
	string getNazwa();
    vector<Student*> getListaStudentow();
    vector<Wykladowca*> getListaWykladowcow();
    vector<Materialy*> getListaMaterialow();
	Wydzial* getWydzial();
	void setNazwa(string nazwa);
	void dodajStudenta(Student* student);
	void usunStudenta(Student* student);
	void dodajWykladowce(Wykladowca* wykladowca);
	void usunWykladowce(Wykladowca* wykladowca);
	void dodajMaterial(Materialy* materialy);
	void usunMaterial(Materialy* materialy);
private:
	string Nazwa;
	vector<Student*> ListaStudentow;
	vector<Wykladowca*> ListaWykladowcow;
	vector<Materialy*> ListaMaterialow;
	Wydzial* wydzial;
};

#endif  //_WYKLAD_H
