//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wyklad.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#include "Wyklad.h"
#include "Wykladowca.h"
#include "Materialy.h"
#include "Wydzial.h"
#include "Student.h"


#include <algorithm>

Wyklad::Wyklad(string nazwa, Wydzial* wydzial) {
    this->Nazwa = nazwa;
    this->wydzial = wydzial;
    this->Haslo = "";
    if (this->wydzial!=nullptr)
        wydzial->dodajNowyWyklad(this);
}

Wyklad::~Wyklad() {
    if (this->wydzial!=nullptr)
        wydzial->usunWyklad(this);

    for(Student* student: this->ListaStudentow){
        student->usunWyklad(this);
    }

    for(Wykladowca* wykladowca: this->ListaWykladowcow){
        wykladowca->usunWyklad(this);
    }

    for(Materialy* materialy: this->ListaMaterialow){
        delete materialy;
    }
}

string Wyklad::getNazwa() {
    return this->Nazwa;
}

vector<Student*> Wyklad::getListaStudentow() {
    return this->ListaStudentow;
}

vector<Wykladowca*> Wyklad::getListaWykladowcow() {
    return this->ListaWykladowcow;
}

vector<Materialy*> Wyklad::getListaMaterialow() {
    return this->ListaMaterialow;
}

Wydzial* Wyklad::getWydzial() {
    return this->wydzial;
}

string Wyklad::getHaslo() {
    return this->Haslo;
}

void Wyklad::setNazwa(string nazwa) {
    this->Nazwa = nazwa;
}

void Wyklad::setHaslo(string haslo) {
    this->Haslo = haslo;
}

void Wyklad::setWydzial(Wydzial* wydzial){
    this->wydzial = wydzial;
}

void Wyklad::dodajStudenta(Student* student) {
    auto it = find(this->ListaStudentow.begin(), this->ListaStudentow.end(), student);
    if (it == this->ListaStudentow.end()) {
        this->ListaStudentow.push_back(student);
        student->dodajDoWykladu(this);
    }
}

void Wyklad::usunStudenta(Student* student) {
    auto it = find(this->ListaStudentow.begin(), this->ListaStudentow.end(), student);
    if (it != this->ListaStudentow.end()) {
        this->ListaStudentow.erase(it);
    }

}

void Wyklad::dodajWykladowce(Wykladowca* wykladowca) {
    auto it = find(this->ListaWykladowcow.begin(), this->ListaWykladowcow.end(), wykladowca);
    if (it == this->ListaWykladowcow.end()) {
        this->ListaWykladowcow.push_back(wykladowca);
        wykladowca->dodajDoWykladu(this);
    }
}

void Wyklad::usunWykladowce(Wykladowca* wykladowca) {
    auto it = find(this->ListaWykladowcow.begin(), this->ListaWykladowcow.end(), wykladowca);
    if (it != this->ListaWykladowcow.end()) {
        this->ListaWykladowcow.erase(it);
    }

}

void Wyklad::dodajMaterialy(Materialy* materialy) {
    auto it = find(this->ListaMaterialow.begin(), this->ListaMaterialow.end(), materialy);
    if (it == this->ListaMaterialow.end()) {
        this->ListaMaterialow.push_back(materialy);
    }
}

void Wyklad::usunMaterialy(Materialy* materialy) {
    auto it = find(this->ListaMaterialow.begin(), this->ListaMaterialow.end(), materialy);
    if (it != this->ListaMaterialow.end()) {
        Materialy* doUsuniecia = *it;
        this->ListaMaterialow.erase(it);
        delete doUsuniecia;
    }
}

