//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wyklad.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#include "Wyklad.h"
#include "Wykladowca.h"
#include "Materialy.h"
#include "Wydzial.h"
#include "Student.h"


#include <iostream>
#include <algorithm> // Wymagane dla funkcji find()

Wyklad::Wyklad(string nazwa, Wydzial* wydzial) {
    this->Nazwa = nazwa;
    this->wydzial = wydzial;
    wydzial->dodajNowyWyklad(this);
}

Wyklad::~Wyklad() {
    for(Student* student: this->ListaStudentow){
        student->usunWyklad(this);
    }

    for(Wykladowca* wykladowca: this->ListaWykladowcow){
        wykladowca->usunWyklad(this);
    }

    for(Materialy* materialy: this->ListaMaterialow){
        delete materialy;
    }
}

string Wyklad::getNazwa() {
    return this->Nazwa;
}

vector<Student*> Wyklad::getListaStudentow() {
    return this->ListaStudentow;
}

vector<Wykladowca*> Wyklad::getListaWykladowcow() {
    return this->ListaWykladowcow;
}

vector<Materialy*> Wyklad::getListaMaterialow() {
    return this->ListaMaterialow;
}

Wydzial* Wyklad::getWydzial() {
    return this->wydzial;
}

void Wyklad::setNazwa(string nazwa) {
    this->Nazwa = nazwa;
}

void Wyklad::dodajStudenta(Student* student) {
    for (Student* stud: this->ListaStudentow)
    {
        if (stud == student){
            cout<<"Student ma juz przypisany ten wyklad." << endl;
            return;
        }
    }

    this->ListaStudentow.push_back(student);
    student->dodajDoWykladu(this);
}

void Wyklad::usunStudenta(Student* student) {
    for (Student* stud: this->ListaStudentow)
    {
        if (stud == student){
            student->usunWyklad(this);
            this->ListaStudentow.erase(find(this->ListaStudentow.begin(), this->ListaStudentow.end(), student));
            return;
        }
    }

    cout<<"Student nie ma przypisanego tego wykladu." << endl;
}

void Wyklad::dodajWykladowce(Wykladowca* wykladowca) {
    for (Wykladowca* wykl: this->ListaWykladowcow)
    {
        if (wykl == wykladowca){
            cout<<"Wykladowca ma juz przypisany ten wyklad." << endl;
            return;
        }
    }

    this->ListaWykladowcow.push_back(wykladowca);
    wykladowca->dodajDoWykladu(this);
}

void Wyklad::usunWykladowce(Wykladowca* wykladowca) {
    for (Wykladowca* wykl: this->ListaWykladowcow)
    {
        if (wykl == wykladowca){
            wykladowca->usunWyklad(this);
            this->ListaWykladowcow.erase(find(this->ListaWykladowcow.begin(), this->ListaWykladowcow.end(), wykladowca));
            return;
        }
    }

    cout<<"Wykladowca nie ma przypisanego tego wykladu." << endl;
}

void Wyklad::dodajMaterial(Materialy* materialy) {
    for (Materialy* mat: this->ListaMaterialow)
    {
        if (mat == materialy){
            cout<<"Materialy zostaly juz dodane." << endl;
            return;
        }
    }

    this->ListaMaterialow.push_back(materialy);
}

void Wyklad::usunMaterial(Materialy* materialy) {
    for (Materialy* mat: this->ListaMaterialow)
    {
        if (mat == materialy){
            this->ListaMaterialow.erase(find(this->ListaMaterialow.begin(), this->ListaMaterialow.end(), materialy));
            delete materialy;
            return;
        }
    }

    cout<<"Nie znaleziono materialow." << endl;
}

