//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.h
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#if !defined(_WYKLADOWCA_H)
#define _WYKLADOWCA_H

#include "User.h"
#include "Wydzial.h"

#include <string>
#include <vector>

using namespace std;

class Wyklad;
class Materialy;

class Wykladowca : public User {
public:
	Wykladowca(string imie, string nazwisko, string login, string haslo);
	~Wykladowca();
	string getImie();
	string getNazwisko();
	vector<Wyklad*> getListaWykladow();
	void setImie(string imie);
	void setNazwisko(string nazwisko);
	void dodajDoWykladu(Wyklad* wyklad);
    Wyklad* utworzWyklad(Wydzial* wydzial, string nazwa);
	void usunWyklad(Wyklad* wyklad);
	vector<Materialy*> przegladajMaterialy(Wyklad* wyklad);
	void dodajMaterialy(Wyklad* wyklad, Materialy* material);
	void usunMaterialy(Wyklad* wyklad, Materialy* material);
private:
	string Imie;
	string Nazwisko;
	vector<Wyklad*> ListaWykladow;
};

#endif  //_WYKLADOWCA_H
