//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#include "Wykladowca.h"
#include "Wyklad.h"
#include "Materialy.h"
#include <iostream>
#include <algorithm> // Wymagane dla funkcji find()

Wykladowca::Wykladowca(string imie, string nazwisko, string login, string haslo) : User(login, haslo) {
    this->Imie = imie;
    this->Nazwisko = nazwisko;
}

Wykladowca::~Wykladowca() {
    for (Wyklad* wyklad: this->ListaWykladow)
    {
        wyklad->usunWykladowce(this);
    }
}

string Wykladowca::getImie() {
    return this->Imie;
}

string Wykladowca::getNazwisko() {
    return this->Nazwisko;
}

vector<Wyklad*> Wykladowca::getListaWykladow() {
    return this->ListaWykladow;
}

void Wykladowca::setImie(string imie) {
    this->Imie = imie;
}

void Wykladowca::setNazwisko(string nazwisko) {
    this->Nazwisko = nazwisko;
}

void Wykladowca::dodajDoWykladu(Wyklad* wyklad) {
    //dodawanie musi odbywać się na rzecz obiektu wykład!
    for (Wyklad* wyk: this->ListaWykladow)
    {
        if (wyk == wyklad){
            cout<<"Wykladowca ma juz przypisany ten wyklad." << endl;
            return;
        }
    }

    this->ListaWykladow.push_back(wyklad);
}

void Wykladowca::usunWyklad(Wyklad* wyklad) {
    vector<Wyklad*> wyklady = this->ListaWykladow;
    for (Wyklad* wyk: wyklady)
    {
        if (wyk == wyklad){
            wyklady.erase(find(wyklady.begin(), wyklady.end(), wyklad));
            return;
        }
    }

    cout<<"Wykladowca nie ma przypisanego tego wykladu." << endl;
}

vector<Materialy*> Wykladowca::przegladajMaterialy(Wyklad* wyklad) {
    return wyklad->getListaMaterialow();
}

void Wykladowca::dodajMaterialy(Wyklad* wyklad, Materialy* material) {
    wyklad->dodajMaterial(material);
}

void Wykladowca::usunMaterialy(Wyklad* wyklad, Materialy* material) {
    wyklad->usunMaterial(material);
}

