//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Wykladowca.cpp
//  @ Date : 24.05.2026
//  @ Author : 
//
//


#include "Wykladowca.h"
#include "Wyklad.h"
#include "Materialy.h"

#include <algorithm>

Wykladowca::Wykladowca(string imie, string nazwisko, string login, string haslo) : User(login, haslo) {
    this->Imie = imie;
    this->Nazwisko = nazwisko;
}

Wykladowca::~Wykladowca() {
    for (Wyklad* wyklad: this->ListaWykladow)
    {
        wyklad->usunWykladowce(this);
    }
}

string Wykladowca::getImie() {
    return this->Imie;
}

string Wykladowca::getNazwisko() {
    return this->Nazwisko;
}

vector<Wyklad*> Wykladowca::getListaWykladow() {
    return this->ListaWykladow;
}

void Wykladowca::setImie(string imie) {
    this->Imie = imie;
}

void Wykladowca::setNazwisko(string nazwisko) {
    this->Nazwisko = nazwisko;
}

void Wykladowca::dodajDoWykladu(Wyklad* wyklad) {
    auto it = find(this->ListaWykladow.begin(), this->ListaWykladow.end(), wyklad);
    if (it == this->ListaWykladow.end()) {
        this->ListaWykladow.push_back(wyklad);
        wyklad->dodajWykladowce(this);
    }
}

Wyklad* Wykladowca::utworzWyklad(Wydzial* wydzial, string nazwa) {
    Wyklad* nowyWyklad = new Wyklad(nazwa, wydzial);
    nowyWyklad->dodajWykladowce(this);
    return nowyWyklad;
}

void Wykladowca::usunWyklad(Wyklad* wyklad) {
    auto it = find(this->ListaWykladow.begin(), this->ListaWykladow.end(), wyklad);
    if (it != this->ListaWykladow.end()) {
        this->ListaWykladow.erase(it);
    }
}

vector<Materialy*> Wykladowca::przegladajMaterialy(Wyklad* wyklad) {
    return wyklad->getListaMaterialow();
}

void Wykladowca::dodajMaterialy(Wyklad* wyklad, Materialy* material) {
    wyklad->dodajMaterialy(material);
}

void Wykladowca::usunMaterialy(Wyklad* wyklad, Materialy* material) {
    wyklad->usunMaterialy(material);
}

